config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :initiatives do
    resources :activities
  end
  resources :outcomes do
    resources :outcome_values
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :initiative
  has_many :outcomes

  def progress
    outcome_progress = outcomes.map { |outcome| outcome.progress }
    return outcome_progress.sum / outcome_progress.count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conflict.rb
class Conflict < ApplicationRecord
  belongs_to :outcome
end

app/models/initiative.rb
class Initiative < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user, class_name: 'User'
  belongs_to :referent, class_name: 'User'
  has_many :activities
end

app/models/initiative_user.rb
class InitiativeUser < ApplicationRecord
  belongs_to :user
  belongs_to :initiative
end

app/models/outcome.rb
class Outcome < ApplicationRecord
  belongs_to :activity
  has_many :outcome_values

  def progress
    if objective_value >= 1
      progress_for_integer
    else
      progress_for_percentage
    end
  end

  def chart_array
    outcome_values.map do |outcome_value|
      [outcome_value.created_at.strftime("%b"), outcome_value.value]
    end
  end

  private

  def progress_for_percentage
    (outcome_values.pluck(:value).sum / outcome_values.pluck(:value).count) / objective_value
  end

  def progress_for_integer
    outcome_values.pluck(:value).sum / objective_value
  end
end

app/models/outcome_value.rb
class OutcomeValue < ApplicationRecord
  belongs_to :outcome
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :initiatives_ent, class_name: 'Initiative', foreign_key: "referent_id"
  has_many :initiatives_ges, class_name: 'Initiative', foreign_key: "user_id"
  mount_uploader :photo, PhotoUploader
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :find_initiative

  def new
    @activity = Activity.new
    authorize @activity
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.initiative = @initiative
    authorize @activity
    if @activity.save
      redirect_to initiative_path(@initiative)
    else
      render :new
    end
  end

  def activity_params
    params.require(:activity).permit(:title, :description, :objective)
  end

  private

  def find_initiative
    @initiative = Initiative.find(params[:initiative_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :home, unless: :skip_pundit?

  def after_sign_in_path_for(_resource)
    initiatives_path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  def index
    if current_user.role == "gestionnaire"
      @initiatives = Initiative.where(user_id: current_user.id)
    elsif current_user.role == "entrepreneur"
      @current_initiative = current_user.initiatives_ent.first
      authorize @current_initiative
      redirect_to initiative_path(@current_initiative)
    end

    if params[:query].present?
      @initiatives = policy_scope(Initiative).where("name ILIKE ?", "%#{params[:query]}%")
      # raise
    else
      @initiatives = policy_scope(Initiative)
    end
  end

  def show
    @initiative = Initiative.find(params[:id])
    authorize @initiative
  end

  def new
    @initiative = Initiative.new
    authorize @initiative
  end

  def create
    @initiative = Initiative.new(initiative_params)
    @initiative.user = current_user
    authorize @initiative
    @initiative.save
    redirect_to initiatives_path
  end

  def edit
    @initiative = Initiative.find(params[:id])
    authorize @initiative
  end

  def update
    @initiative = Initiative.find(params[:id])
    authorize @initiative
    @initiative.update(initiative_params)
    redirect_to initiative_path(@initiative)
  end

  def destroy
    @initiative = Initiative.find(params[:id])
    authorize @initiative
    @initiative.destroy
    redirect_to initiatives_path
  end

  def initiative_params
    params.require(:initiative).permit(:name, :description, :sector_activity, :country, :budget, :photo)
  end
end

app/controllers/outcome_values_controller.rb
class OutcomeValuesController < ApplicationController
  def new
    @outcome = Outcome.find(params[:outcome_id])
    authorize @outcome
    @outcome_value = OutcomeValue.new
    @outcome_values = OutcomeValue.all
    ov_array
  end

  def create
    @outcome_value = OutcomeValue.new(outcome_params)
    @outcome_value.outcome_id = params[:outcome_id]
    authorize @outcome_value
    @outcome_value.save
    redirect_to initiative_path(@outcome_value.outcome.activity.initiative)
  end

  private

  def outcome_params
    params.require(:outcome_value).permit(:value)
  end

  def ov_array
    @ov_array = @outcome_values.map do |outcome_value|
      [outcome_value.created_at.strftime("%b"), outcome_value.value]
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  skip_after_action :verify_policy_scoped, only: [:home]
  skip_after_action :verify_authorized, only: [:home]

  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/new.html.erb
<!--   create_table "activities", force: :cascade do |t|
    t.string "title"
    t.text "description"
    t.bigint "initiative_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.float "objective"
    t.index ["initiative_id"], name: "index_activities_on_initiative_id"
  end -->

<div class="container">
<h1> Add a new activity </h1>
  <%= simple_form_for [@initiative, @activity] do |f| %>
    <%= f.input :title, label:"Title" %>
    <%= f.input :description %>
    <%= f.input :objective, label: "Objective"%>
    <div class="submit">
    <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/initiatives/index.html.erb
<div class="container container-global">
  <div class="row">
    <div class="col col-sm-3 offset-md-1">
      <div class="sidebar">
        <div class="imglog"><%= image_tag("link.png")%></div>
        <div class="arbre"><%= image_tag("arbre.svg") %></div>
        <div class="about"></div>
     </div>
    </div>
    <div class="col col-sm-8">
        <%= render "shared/navbar" %>

<div class="mini-container">
<%= form_tag initiatives_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find an initiative ..."%>
<% end %>
</div>

<div class="results">
  <div class="row">
    <% @initiatives.each do |initiative| %>
      <div class="col-xs-12 col-sm-6">
        <div class="card-product">
          <%= cl_image_tag initiative.photo, class:"cover", width: 120, height: 120  %>
          <div class="card-product-infos">
            <%= link_to initiative.name, initiative_path(initiative)  %>
            <p><%= initiative.description %></p>
            <div class="localisation">
            <%= image_tag "placeholder.png", width: "25px", height: "25px" %>
            <p><%= initiative.country %></p>
            </div>
            <p><strong><%= initiative.sector_activity %></strong></p>
          </div>
        </div>
      </div>
  <% end %>
</div>
</div>
  <div class="btn-add">
    <%= link_to " + Add an initiative", new_initiative_path %>
  </div>
</div>
    </div>
  </div>
</div>

app/views/initiatives/new.html.erb
<div class="container">
<h1> Add an initiative </h1>
  <%= simple_form_for(@initiative) do |f| %>
    <%= f.input :name, label:"Name" %>
    <%= f.input :description %>
    <%= f.input :sector_activity, label: "Activity sector"%>
    <%= f.input :country, label: "Country"%>
    <%= f.input :budget, label: 'Budget' %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <div class="submit">
    <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/initiatives/show.html.erb
<%= javascript_pack_tag 'chartkick' %>

<div class="container container-global">
  <div class="row">
    <div class="col col-sm-3 offset-md-1">
      <div class="initiative-sidebar">
        <div class="imglog"><%= image_tag("link.png")%></div>
        <%= cl_image_tag @initiative.photo, class: 'ini-photo' %>
        <div class="ini-sdg">
            <%= image_tag "sdg3.png", width:"40", height:"40" %>
            <%= image_tag "sdg5.png", width:"40", height:"40" %>
            <%= image_tag "sdg6.png", width:"40", height:"40" %>
        </div>
          <div class="characteristics">
            <div class="chara">
              <%= image_tag("globe-europe-solid.svg") %>
              <%= @initiative.country %>
            </div>
            <div class="chara">
              <%= image_tag("hand-holding-usd-solid.svg") %>
              <%= @initiative.budget %>
            </div>
            <div class="chara">
              <%= image_tag("calendar-alt-solid.svg") %>
              <p>2005</p>
            </div>
            <div class="chara">
              <%= image_tag("hand-holding-heart-solid.svg") %>
              <p>Hospitals</p>
            </div>
          </div>
        <div class="fin">
        </div>
      </div>
    </div>
  <div class="col col-sm-8">
    <%= render "shared/navbar" %>
  <div class="dashboard">
    <h2><%= @initiative.name %></h2>
    <h3><%= @initiative.description %></h3>
    <div class="activities">
    <% @initiative.activities.each_with_index do |activity, index| %>
        <div class = "activity-chart">
          <div class="graph">
            <div class ="number"> <%= (activity.progress*100).round %>% </div>
            <%= pie_chart [["positif", activity.progress],["negatif", 1 - activity.progress]], colors: ["#44AEBC", "#d8cbbb"], donut: true,library: {cutoutPercentage: 65}, legend: false, width: "80px", height: "80px"%>
          </div>
            <h2><%= activity.title %></h2>
        </div>
        <div class="values-progression">
          <% activity.outcomes.each do |outcome| %>
          <div class="outcome-first">
            <h3><%= outcome.title%></h3>
            <% if current_user.role == "entrepreneur" %>
            <div class="boutons">
              <div class="btn-primary"><%= link_to "add a new value", new_outcome_outcome_value_path(outcome)%></div>
              <div class="btn-danger"><%= link_to "declare conflict", new_outcome_outcome_value_path(outcome)%></div>
            </div>
            <% end %>
          </div>
          <div class="outcome-second">
            <div class = "metrics">
              <div class="met">
                <div class="indic">Objective</div>
                <div class="nb"><%= outcome.objective_value.round %></div>
              </div>
              <div class="met">
                <div class="indic">Progress</div>
                <div class="nb"><%= (outcome.progress*100).round %>%</div>
              </div>
              <div class="met">
                <div class="indic">Last update</div>
                <div class="nb"><%= outcome.outcome_values.last.created_at.strftime("%D") %> </div>
              </div>
            </div>
          <%#= line_chart outcome.chart_array, colors: ["#44AEBC", "#d8cbbb"], donut: true, legend: false, width: "70%"%>
          <%= column_chart outcome.chart_array, colors: ["#44AEBC", "#d8cbbb"], legend: false, width: "70%"%>
          </div>
                <% end %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sial Impact</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
     <link href="https://fonts.googleapis.com/css?family=K2D:200,300,400,500,600" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style="background-color:#FFF">
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/outcome_values/new.html.erb
<%= javascript_pack_tag 'chartkick' %>

<div class="container container-global">
  <div class="row">
    <div class="col col-sm-3 offset-md-1">
      <div class="sidebar">
        <div class="imglog"><%= image_tag("link.png")%></div>
        <div class="arbre"><%= image_tag("arbre.svg") %></div>
        <div class="about"></div>
     </div>
    </div>
    <div class="col col-sm-8">
      <%= render "shared/navbar" %>
      <div class="container">
  <div class="history">
    <div class="title"><%= @outcome.title %></div>
    <div class="yobj"> Yearly objective : <%= @outcome.objective_value %></div>
    <div class="prg"> Progress : <%= (@outcome.progress*100).round %>%</div>
  </div>
  <div class="info">
      <table class="tabulae">
        <tr class="Intitules">
          <th>Date</th>
          <th>Outcome</th>
        </tr>
    <% @outcome.outcome_values.each do |outcome_value|%>
        <tr>
          <td><%= outcome_value.created_at.strftime("%D") %></td>
          <td><%= outcome_value.value %></td>
        </tr>
      <% end %>
    </table>
    <%= column_chart @outcome.chart_array, colors: ["#44AEBC", "#EEE"], legend: false, width: "70%", height: "auto"%>
    </div>
  <div class="new-value">
  <%= simple_form_for [@outcome, @outcome_value] do |f| %>
    <%= f.input :value %>
    <%= f.button :submit, class: "btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container container-global">
  <div class="row">
    <div class="col col-sm-3 offset-md-1">
      <div class="sidebar">
        <div class="imglog"><%= image_tag("link.png")%></div>
        <div class="arbre"><%= image_tag("arbre.svg") %></div>
        <div class="about"></div>
     </div>
    </div>
    <div class="col col-sm-8">
      <%= render "shared/navbar" %>
      <div class="accroche">
        <div class="gros-titre"> SIAL IMPACT </div>
        <div class="second-titre"> CONNECTING GIVERS AND DOERS </div>
        <div class="texte1"> Sial Impact is a an outcome-based software that connect doers on the field with managers and donators </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <% if user_signed_in? %>
          <% if current_user.role == "entrepreneur"%>
            <%= link_to "Inputs", initiatives_path, class: "navbar-wagon-item navbar-wagon-link" %>
            <%= link_to "Messages", initiatives_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% else %>
            <%= link_to "Dashboard", initiatives_path, class: "navbar-wagon-item navbar-wagon-link" %>
            <%= link_to "Initiatives", initiatives_path, class: "navbar-wagon-item navbar-wagon-link" %>
            <%= link_to "Messages", initiatives_path, class: "navbar-wagon-item navbar-wagon-link" %>
            <li class="nav-item dropdown">
          <% end %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= link_to t(".sign_in", default: "Manager"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to t(".sign_in", default: "Entrepreneur"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <li>
              <%= link_to initiatives_path do %>
                <i class="fa fa-user"></i> <%= t(".initiatives", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path  do %>
                <i class="fa fa-cog"></i>  <%= t(".initiatives", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
        </ul>
      </li>
    </ul>
  </div>
</div>